apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap-repo.yaml
  - base.yaml
  - partition.yaml
  - entitlements.yaml
  - legal.yaml
  - schema.yaml
  - storage.yaml
  - indexer.yaml
  - file.yaml
  - search.yaml
  - workflow.yaml
  - user-init.yaml
